-- Catálogo inicial Farmacia Oasis / Bioasis.
-- Ejecutar en el SQL editor de Supabase.
-- Las imágenes deben estar en /public/products con los nombres documentados en public/products/README.md.
-- Los productos quedan cargados como "consultar" porque no se informaron precios finales.
-- Para vender online, actualizar price, promotional_price y stock desde Supabase.

insert into products (
  slug,
  name,
  description,
  price,
  promotional_price,
  weight_kg,
  height_cm,
  width_cm,
  depth_cm,
  stock,
  sku,
  barcode,
  is_active,
  image_url,
  categories,
  tags
) values
(
  'kit-limpieza-facial-completa-leche-tonico-exfoliante',
  'Kit Limpieza Facial Completa – Leche + Tónico + Exfoliante',
  'Rutina completa de limpieza facial con leche de limpieza, tónico facial descongestivo y exfoliante facial Suavidad Natural. Ideal para preparar, refrescar y renovar la piel.',
  0,
  null,
  0.45,
  16,
  18,
  6,
  0,
  'OASIS-KIT-LIMPIEZA-01',
  null,
  true,
  '/products/01-kit-limpieza-facial-completa.webp',
  array['Limpieza facial', 'Kits'],
  array['leche de limpieza', 'tónico facial', 'exfoliante', 'rutina facial']
),
(
  'balsamo-reparador-labial-vitamina-k-vitamina-e-15g',
  'Bálsamo Reparador Labial con Vitamina K y Vitamina E – 15 g',
  'Bálsamo reparador para labios secos o sensibilizados. Ayuda a proteger, nutrir y suavizar la zona labial con vitaminas K y E.',
  0,
  null,
  0.08,
  5,
  6,
  6,
  0,
  'OASIS-BALSAMO-LABIAL-15G',
  null,
  true,
  '/products/02-balsamo-reparador-labial-vitamina-k-e-15g.webp',
  array['Labios', 'Reparadores'],
  array['bálsamo labial', 'vitamina k', 'vitamina e', 'reparador']
),
(
  'emulsion-hidratante-fitoesteroles-fps-30',
  'Emulsión Hidratante con Fitoesteroles FPS 30',
  'Emulsión facial hidratante con fitoesteroles y FPS 30. Aporta hidratación diaria y protección solar para acompañar la rutina de día.',
  0,
  null,
  0.15,
  13,
  5,
  5,
  0,
  'OASIS-EMULSION-FPS30',
  null,
  true,
  '/products/03-emulsion-hidratante-fitoesteroles-fps-30.webp',
  array['Hidratación', 'Protección solar'],
  array['emulsión hidratante', 'fitoesteroles', 'fps 30', 'día']
),
(
  'kit-antiage-completo-rutina-dia-noche',
  'Kit Antiage Completo – Rutina Día & Noche',
  'Kit antiage completo para rutina de día y noche. Incluye crema antiage día, crema antiage noche y gel contorno de ojos Efecto Seda.',
  0,
  null,
  0.35,
  14,
  20,
  8,
  0,
  'OASIS-KIT-ANTIAGE-04',
  null,
  true,
  '/products/04-kit-antiage-completo-dia-noche.webp',
  array['Antiage', 'Kits'],
  array['antiage', 'rutina día', 'rutina noche', 'contorno de ojos']
),
(
  'crema-antiage-noche-oasis-night-repair-50g',
  'Crema Antiage Noche – Oasis Night Repair (50 g)',
  'Crema antiage de noche Oasis Night Repair. Formulada para acompañar la reparación nocturna, aportar hidratación y mejorar la apariencia de la piel.',
  0,
  null,
  0.12,
  6,
  7,
  7,
  0,
  'OASIS-NIGHT-REPAIR-50G',
  null,
  true,
  '/products/05-crema-antiage-noche-oasis-night-repair-50g.webp',
  array['Antiage', 'Cremas faciales'],
  array['crema noche', 'night repair', 'antiage', '50g']
),
(
  'crema-antiage-dia-oasis-day-balance-50g',
  'Crema Antiage Día – Oasis Day Balance (50 g)',
  'Crema antiage de día Oasis Day Balance. Textura de uso diario para hidratar, proteger y acompañar el cuidado facial durante el día.',
  0,
  null,
  0.12,
  6,
  7,
  7,
  0,
  'OASIS-DAY-BALANCE-50G',
  null,
  true,
  '/products/06-crema-antiage-dia-oasis-day-balance-50g.webp',
  array['Antiage', 'Cremas faciales'],
  array['crema día', 'day balance', 'antiage', '50g']
),
(
  'gel-contorno-ojos-cafeina-efecto-seda',
  'Gel Contorno de Ojos con Cafeína – Efecto Seda',
  'Gel liviano para contorno de ojos con cafeína y efecto seda. Ayuda a refrescar la mirada y mejorar la sensación de cansancio.',
  0,
  null,
  0.06,
  12,
  4,
  4,
  0,
  'OASIS-CONTORNO-OJOS-CAFEINA',
  null,
  true,
  '/products/07-gel-contorno-ojos-cafeina-efecto-seda.webp',
  array['Contorno de ojos', 'Antiage'],
  array['cafeína', 'efecto seda', 'ojeras', 'mirada']
),
(
  'espuma-limpieza-facial-descongestiva-te-verde-malva',
  'Espuma de Limpieza Facial Descongestiva – Té Verde & Malva',
  'Espuma de limpieza facial descongestiva con té verde y malva. Limpia suavemente y deja sensación fresca y confortable.',
  0,
  null,
  0.15,
  16,
  5,
  5,
  0,
  'OASIS-ESPUMA-TE-VERDE-MALVA',
  null,
  true,
  '/products/08-espuma-limpieza-facial-te-verde-malva.webp',
  array['Limpieza facial'],
  array['espuma facial', 'té verde', 'malva', 'descongestiva']
),
(
  'exfoliante-facial-suavidad-natural',
  'Exfoliante Facial Suavidad Natural',
  'Exfoliante facial Suavidad Natural. Ayuda a remover impurezas y células muertas, dejando la piel más suave y renovada.',
  0,
  null,
  0.15,
  13,
  5,
  5,
  0,
  'OASIS-EXFOLIANTE-SUAVIDAD',
  null,
  true,
  '/products/09-exfoliante-facial-suavidad-natural.webp',
  array['Limpieza facial', 'Exfoliantes'],
  array['exfoliante facial', 'suavidad natural', 'renovación']
),
(
  'agua-micelar-facial',
  'Agua Micelar Facial',
  'Agua micelar facial para limpieza diaria. Ayuda a retirar impurezas y maquillaje dejando sensación fresca y suave.',
  0,
  null,
  0.18,
  14,
  5,
  5,
  0,
  'OASIS-AGUA-MICELAR',
  null,
  true,
  '/products/10-agua-micelar-facial.webp',
  array['Limpieza facial'],
  array['agua micelar', 'limpieza', 'desmaquillante']
),
(
  'crema-cuello-escote-40',
  'Crema de Cuello y Escote +40',
  'Crema específica para cuello y escote +40. Acompaña el cuidado de zonas delicadas con hidratación y efecto piel más confortable.',
  0,
  null,
  0.12,
  13,
  5,
  5,
  0,
  'OASIS-CUELLO-ESCOTE-40',
  null,
  true,
  '/products/11-crema-cuello-escote-40.webp',
  array['Antiage', 'Cremas corporales'],
  array['cuello', 'escote', '+40', 'volumen']
),
(
  'gel-flebotonico-250g-circulacion-piernas-cansadas',
  'Gel Flebotónico 250 g – Circulación y piernas cansadas',
  'Gel flebotónico de 250 g para piernas cansadas. Fórmula refrescante para masajes de alivio y cuidado de la circulación.',
  0,
  null,
  0.32,
  9,
  9,
  9,
  0,
  'OASIS-GEL-FLEBOTONICO-250G',
  null,
  true,
  '/products/12-gel-flebotonico-250g.webp',
  array['Cuidado corporal', 'Piernas'],
  array['gel flebotónico', 'piernas cansadas', 'circulación', '250g']
),
(
  'agua-termal-facial',
  'Agua Termal Facial',
  'Agua termal facial en spray para refrescar, tonificar y acompañar la hidratación diaria de la piel.',
  0,
  null,
  0.15,
  17,
  4,
  4,
  0,
  'OASIS-AGUA-TERMAL',
  null,
  true,
  '/products/13-agua-termal-facial.webp',
  array['Hidratación', 'Facial'],
  array['agua termal', 'spray facial', 'aqua vital']
),
(
  'serum-tensor-botox-argireline-10',
  'Serum tensor botox con argireline 10%',
  'Serum tensor tipo botox sin aguja con argireline 10%. Tratamiento cosmético para mejorar la apariencia de líneas de expresión.',
  0,
  null,
  0.08,
  13,
  4,
  4,
  0,
  'OASIS-SERUM-TENSOR-ARGIRELINE-10',
  null,
  true,
  '/products/14-serum-tensor-botox-argireline-10.webp',
  array['Serums', 'Antiage'],
  array['serum tensor', 'argireline', 'botox sin aguja', 'antiage']
),
(
  'serum-regenerador-pepitas-uva',
  'Serum regenerador pepitas de uva',
  'Serum regenerador con pepitas de uva. Ayuda a nutrir y mejorar la apariencia de la piel con una textura liviana.',
  0,
  null,
  0.08,
  13,
  4,
  4,
  0,
  'OASIS-SERUM-PEPITAS-UVA',
  null,
  true,
  '/products/15-serum-regenerador-pepitas-uva.webp',
  array['Serums', 'Regeneradores'],
  array['serum regenerador', 'pepitas de uva', 'nutrición facial']
),
(
  'serum-vit-c-acido-hialuronico',
  'Serum Vit C + Ácido Hialurónico',
  'Serum facial con vitamina C y ácido hialurónico. Aporta efecto luminosidad, hidratación y frescura para la rutina diaria.',
  0,
  null,
  0.08,
  13,
  4,
  4,
  0,
  'OASIS-SERUM-VITC-HIALURONICO',
  null,
  true,
  '/products/16-serum-vit-c-acido-hialuronico.webp',
  array['Serums', 'Hidratación'],
  array['vitamina c', 'ácido hialurónico', 'hidra glow', 'luminosidad']
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  weight_kg = excluded.weight_kg,
  height_cm = excluded.height_cm,
  width_cm = excluded.width_cm,
  depth_cm = excluded.depth_cm,
  sku = excluded.sku,
  image_url = excluded.image_url,
  categories = excluded.categories,
  tags = excluded.tags,
  is_active = excluded.is_active,
  updated_at = now();
