import type { Product } from "@/lib/types"

const now = "2026-01-01T00:00:00.000Z"

const productBase = {
  price: 0,
  promotional_price: null,
  stock: 0,
  barcode: null,
  is_active: true,
  image_url: null,
  created_at: now,
  updated_at: now,
} satisfies Partial<Product>

export const fallbackProducts: Product[] = [
  {
    ...productBase,
    id: "fallback-01",
    image_url: "/products/01-kit-limpieza-facial-completa.webp",
    slug: "kit-limpieza-facial-completa-leche-tonico-exfoliante",
    name: "Kit Limpieza Facial Completa – Leche + Tónico + Exfoliante",
    description:
      "Rutina completa de limpieza facial con leche de limpieza, tónico facial descongestivo y exfoliante facial Suavidad Natural.",
    weight_kg: 0.45,
    height_cm: 16,
    width_cm: 18,
    depth_cm: 6,
    sku: "OASIS-KIT-LIMPIEZA-01",
    categories: ["Limpieza facial", "Kits"],
    tags: ["leche de limpieza", "tónico facial", "exfoliante"],
  },
  {
    ...productBase,
    id: "fallback-02",
    image_url: "/products/02-balsamo-reparador-labial-vitamina-k-e-15g.webp",
    slug: "balsamo-reparador-labial-vitamina-k-vitamina-e-15g",
    name: "Bálsamo Reparador Labial con Vitamina K y Vitamina E – 15 g",
    description:
      "Bálsamo reparador para labios secos o sensibilizados. Ayuda a proteger, nutrir y suavizar la zona labial.",
    weight_kg: 0.08,
    height_cm: 5,
    width_cm: 6,
    depth_cm: 6,
    sku: "OASIS-BALSAMO-LABIAL-15G",
    categories: ["Labios", "Reparadores"],
    tags: ["bálsamo labial", "vitamina k", "vitamina e"],
  },
  {
    ...productBase,
    id: "fallback-03",
    image_url: "/products/03-emulsion-hidratante-fitoesteroles-fps-30.webp",
    slug: "emulsion-hidratante-fitoesteroles-fps-30",
    name: "Emulsión Hidratante con Fitoesteroles FPS 30",
    description:
      "Emulsión facial hidratante con fitoesteroles y FPS 30 para acompañar la rutina de día.",
    weight_kg: 0.15,
    height_cm: 13,
    width_cm: 5,
    depth_cm: 5,
    sku: "OASIS-EMULSION-FPS30",
    categories: ["Hidratación", "Protección solar"],
    tags: ["emulsión hidratante", "fitoesteroles", "fps 30"],
  },
  {
    ...productBase,
    id: "fallback-04",
    image_url: "/products/04-kit-antiage-completo-dia-noche.webp",
    slug: "kit-antiage-completo-rutina-dia-noche",
    name: "Kit Antiage Completo – Rutina Día & Noche",
    description:
      "Kit antiage con crema de día, crema de noche y gel contorno de ojos Efecto Seda.",
    weight_kg: 0.35,
    height_cm: 14,
    width_cm: 20,
    depth_cm: 8,
    sku: "OASIS-KIT-ANTIAGE-04",
    categories: ["Antiage", "Kits"],
    tags: ["antiage", "rutina día", "rutina noche"],
  },
  {
    ...productBase,
    id: "fallback-05",
    image_url: "/products/05-crema-antiage-noche-oasis-night-repair-50g.webp",
    slug: "crema-antiage-noche-oasis-night-repair-50g",
    name: "Crema Antiage Noche – Oasis Night Repair (50 g)",
    description:
      "Crema antiage de noche para acompañar la reparación nocturna e hidratar la piel.",
    weight_kg: 0.12,
    height_cm: 6,
    width_cm: 7,
    depth_cm: 7,
    sku: "OASIS-NIGHT-REPAIR-50G",
    categories: ["Antiage", "Cremas faciales"],
    tags: ["crema noche", "night repair", "antiage"],
  },
  {
    ...productBase,
    id: "fallback-06",
    image_url: "/products/06-crema-antiage-dia-oasis-day-balance-50g.webp",
    slug: "crema-antiage-dia-oasis-day-balance-50g",
    name: "Crema Antiage Día – Oasis Day Balance (50 g)",
    description:
      "Crema antiage de día para hidratar y acompañar el cuidado facial diario.",
    weight_kg: 0.12,
    height_cm: 6,
    width_cm: 7,
    depth_cm: 7,
    sku: "OASIS-DAY-BALANCE-50G",
    categories: ["Antiage", "Cremas faciales"],
    tags: ["crema día", "day balance", "antiage"],
  },
  {
    ...productBase,
    id: "fallback-07",
    image_url: "/products/07-gel-contorno-ojos-cafeina-efecto-seda.webp",
    slug: "gel-contorno-ojos-cafeina-efecto-seda",
    name: "Gel Contorno de Ojos con Cafeína – Efecto Seda",
    description:
      "Gel liviano para contorno de ojos con cafeína y efecto seda para refrescar la mirada.",
    weight_kg: 0.06,
    height_cm: 12,
    width_cm: 4,
    depth_cm: 4,
    sku: "OASIS-CONTORNO-OJOS-CAFEINA",
    categories: ["Contorno de ojos", "Antiage"],
    tags: ["cafeína", "efecto seda", "ojeras"],
  },
  {
    ...productBase,
    id: "fallback-08",
    image_url: "/products/08-espuma-limpieza-facial-te-verde-malva.webp",
    slug: "espuma-limpieza-facial-descongestiva-te-verde-malva",
    name: "Espuma de Limpieza Facial Descongestiva – Té Verde & Malva",
    description:
      "Espuma de limpieza facial descongestiva con té verde y malva.",
    weight_kg: 0.15,
    height_cm: 16,
    width_cm: 5,
    depth_cm: 5,
    sku: "OASIS-ESPUMA-TE-VERDE-MALVA",
    categories: ["Limpieza facial"],
    tags: ["espuma facial", "té verde", "malva"],
  },
  {
    ...productBase,
    id: "fallback-09",
    image_url: "/products/09-exfoliante-facial-suavidad-natural.webp",
    slug: "exfoliante-facial-suavidad-natural",
    name: "Exfoliante Facial Suavidad Natural",
    description:
      "Exfoliante facial para remover impurezas y dejar la piel suave y renovada.",
    weight_kg: 0.15,
    height_cm: 13,
    width_cm: 5,
    depth_cm: 5,
    sku: "OASIS-EXFOLIANTE-SUAVIDAD",
    categories: ["Limpieza facial", "Exfoliantes"],
    tags: ["exfoliante facial", "suavidad natural"],
  },
  {
    ...productBase,
    id: "fallback-10",
    image_url: "/products/10-agua-micelar-facial.webp",
    slug: "agua-micelar-facial",
    name: "Agua Micelar Facial",
    description: "Agua micelar facial para limpieza diaria y retiro de impurezas.",
    weight_kg: 0.18,
    height_cm: 14,
    width_cm: 5,
    depth_cm: 5,
    sku: "OASIS-AGUA-MICELAR",
    categories: ["Limpieza facial"],
    tags: ["agua micelar", "limpieza", "desmaquillante"],
  },
  {
    ...productBase,
    id: "fallback-11",
    image_url: "/products/11-crema-cuello-escote-40.webp",
    slug: "crema-cuello-escote-40",
    name: "Crema de Cuello y Escote +40",
    description: "Crema específica para cuello y escote +40 con hidratación y efecto confortable.",
    weight_kg: 0.12,
    height_cm: 13,
    width_cm: 5,
    depth_cm: 5,
    sku: "OASIS-CUELLO-ESCOTE-40",
    categories: ["Antiage", "Cremas corporales"],
    tags: ["cuello", "escote", "+40"],
  },
  {
    ...productBase,
    id: "fallback-12",
    image_url: "/products/12-gel-flebotonico-250g.webp",
    slug: "gel-flebotonico-250g-circulacion-piernas-cansadas",
    name: "Gel Flebotónico 250 g – Circulación y piernas cansadas",
    description: "Gel flebotónico refrescante para masajes de alivio en piernas cansadas.",
    weight_kg: 0.32,
    height_cm: 9,
    width_cm: 9,
    depth_cm: 9,
    sku: "OASIS-GEL-FLEBOTONICO-250G",
    categories: ["Cuidado corporal", "Piernas"],
    tags: ["gel flebotónico", "piernas cansadas", "circulación"],
  },
  {
    ...productBase,
    id: "fallback-13",
    image_url: "/products/13-agua-termal-facial.webp",
    slug: "agua-termal-facial",
    name: "Agua Termal Facial",
    description: "Agua termal facial en spray para refrescar y acompañar la hidratación diaria.",
    weight_kg: 0.15,
    height_cm: 17,
    width_cm: 4,
    depth_cm: 4,
    sku: "OASIS-AGUA-TERMAL",
    categories: ["Hidratación", "Facial"],
    tags: ["agua termal", "spray facial"],
  },
  {
    ...productBase,
    id: "fallback-14",
    image_url: "/products/14-serum-tensor-botox-argireline-10.webp",
    slug: "serum-tensor-botox-argireline-10",
    name: "Serum tensor botox con argireline 10%",
    description: "Serum tensor tipo botox sin aguja con argireline 10%.",
    weight_kg: 0.08,
    height_cm: 13,
    width_cm: 4,
    depth_cm: 4,
    sku: "OASIS-SERUM-TENSOR-ARGIRELINE-10",
    categories: ["Serums", "Antiage"],
    tags: ["serum tensor", "argireline", "botox sin aguja"],
  },
  {
    ...productBase,
    id: "fallback-15",
    image_url: "/products/15-serum-regenerador-pepitas-uva.webp",
    slug: "serum-regenerador-pepitas-uva",
    name: "Serum regenerador pepitas de uva",
    description: "Serum regenerador con pepitas de uva para nutrir y mejorar la apariencia de la piel.",
    weight_kg: 0.08,
    height_cm: 13,
    width_cm: 4,
    depth_cm: 4,
    sku: "OASIS-SERUM-PEPITAS-UVA",
    categories: ["Serums", "Regeneradores"],
    tags: ["serum regenerador", "pepitas de uva"],
  },
  {
    ...productBase,
    id: "fallback-16",
    image_url: "/products/16-serum-vit-c-acido-hialuronico.webp",
    slug: "serum-vit-c-acido-hialuronico",
    name: "Serum Vit C + Ácido Hialurónico",
    description: "Serum facial con vitamina C y ácido hialurónico para luminosidad e hidratación.",
    weight_kg: 0.08,
    height_cm: 13,
    width_cm: 4,
    depth_cm: 4,
    sku: "OASIS-SERUM-VITC-HIALURONICO",
    categories: ["Serums", "Hidratación"],
    tags: ["vitamina c", "ácido hialurónico", "hidra glow"],
  },
]
